name: Calculator CI/CD

on:
  push:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Docker/Multi-stage-distroless-calculator

    env:
      IMAGE_NAME: pooja160701/calculator-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run tests
        run: pytest tests/

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

      - name: Done
        run: echo "Deployed to DockerHub"