name: Alert Automation CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Alert_Automation_Using_AWS_CloudWatch_+_SNS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install flake8

      - name: Lint (non-blocking)
        run: flake8 . || true

      - name: Build Docker
        run: docker build -t cpu-spike .

      - name: Run container
        run: docker run cpu-spike